Consider an experiment where  𝑛  fair die are rolled. Simulate the experiment using calls to numpy.random.uniform. Define  𝑍  as the sum of the face values. Estimate the probability mass function (PMF) (hint: frequency distributions), range, expectation and variance for  𝑍 . Also plot the estimated probability mass function, together with the theoretical PMF. (Hint : see this SO question).

In [ ]:
import numpy as np
import matplotlib.pyplot as plt


In [14]:
num_die = 10
num_trials = 1000

exp_data = np.random.uniform(1,7,(num_trials,num_die))

exp_data = np.floor(exp_data).astype("int")

Z = np.sum(exp_data,axis=1)

Z

array([36, 38, 34, 37, 35, 36, 34, 31, 34, 38, 38, 30, 33, 31, 24, 37, 31,
       38, 42, 41, 41, 30, 39, 30, 46, 31, 34, 35, 29, 42, 38, 30, 35, 33,
       39, 37, 41, 43, 43, 44, 32, 45, 26, 37, 31, 29, 36, 32, 47, 24, 36,
       30, 33, 34, 36, 41, 28, 38, 32, 32, 42, 37, 44, 35, 43, 30, 24, 36,
       38, 30, 39, 28, 47, 27, 31, 38, 23, 38, 31, 45, 34, 42, 26, 28, 29,
       23, 35, 37, 25, 26, 28, 38, 41, 40, 28, 37, 22, 28, 28, 37, 35, 36,
       34, 40, 37, 35, 31, 34, 32, 33, 39, 40, 42, 39, 38, 30, 46, 26, 38,
       35, 37, 37, 39, 28, 36, 25, 44, 28, 34, 40, 25, 33, 34, 45, 33, 45,
       36, 46, 35, 34, 36, 32, 37, 28, 43, 33, 31, 34, 28, 32, 38, 40, 45,
       39, 36, 37, 38, 28, 40, 38, 33, 42, 43, 39, 33, 35, 30, 39, 42, 31,
       34, 30, 33, 27, 35, 40, 40, 28, 33, 35, 30, 36, 33, 44, 35, 29, 35,
       38, 27, 36, 37, 41, 39, 27, 28, 35, 36, 28, 42, 45, 32, 38, 35, 22,
       31, 37, 25, 37, 29, 35, 41, 31, 37, 31, 26, 33, 40, 38, 22, 41, 29,
       41, 28, 31, 42, 40

In [1]:

import numpy as np 
  
in_array = [.5, 1.5, 2.5, 3.5, 4.5, 10.1] 
print ("Input array : \n", in_array) 
  
flooroff_values = np.floor(in_array) 
print ("\nRounded values : \n", flooroff_values) 
  
  
in_array = [.53, 1.54, .71] 
print ("\nInput array : \n", in_array) 
  
flooroff_values = np.floor(in_array) 
print ("\nRounded values : \n", flooroff_values) 
  
in_array = [.5538, 1.33354, .71445] 
print ("\nInput array : \n", in_array) 
  
flooroff_values = np.floor(in_array) 
print ("\nRounded values : \n", flooroff_values) 

Input array : 
 [0.5, 1.5, 2.5, 3.5, 4.5, 10.1]

Rounded values : 
 [ 0.  1.  2.  3.  4. 10.]

Input array : 
 [0.53, 1.54, 0.71]

Rounded values : 
 [0. 1. 0.]

Input array : 
 [0.5538, 1.33354, 0.71445]

Rounded values : 
 [0. 1. 0.]


In [5]:
import numpy as np 
a = np.array([5,2,6,2,7,5,6,8,2,9]) 


u = np.unique(a) 

print(u)


u,indices = np.unique(a, return_index = True) 
print(u)
print(indices)

u,indices = np.unique(a,return_inverse = True) 
print(u)
print(indices) 
 

u,indices = np.unique(a,return_counts = True) 
print(u)
print(indices)



[2 5 6 7 8 9]
[2 5 6 7 8 9]
[1 0 2 4 7 9]
[2 5 6 7 8 9]
[1 0 2 0 3 1 2 4 0 5]
[2 5 6 7 8 9]
[3 2 2 1 1 1]
